### ISSUE TITLE
Publish declaration files

### ISSUE THREAD

**Issue by pburgmer** [hugo19941994/jwks-fetch#114]
Hi,

Thanks for this really helpful library.

Could you please publish TypeScript declaration files.
TypeScript users will then be able to use ESM imports instead of require and will get auto completion.

Kind regards,
Philipp

**Comment by hugo19941994** [comment]
Hey. I actually used this recently in a Typescript project and I added the Typescript declarations in a private fork.

I'll try to add those today. Maybe drop version 1.0.0 too

**Comment by hugo19941994** [comment]
Declarations files published! Thanks for opening the issue, as I already did this but never bothered to upload it :+1:

**Comment by pburgmer** [comment]
You're welcome. Thanks for adding.

**Comment by pburgmer** [comment]
Just installed the new version and found a small issue: Auto Import in IntelliJ is from jwks-fetch/dist, because the declaration files are located there. If I change it manually to just jwks-fetch it works, but I can not jump to declaration.
Could you please add ```"typings": "dist/index.d.ts"``` to package.json. Then auto import should detect just jwks-fetch and jumpto declaration works.

**Comment by hugo19941994** [comment]
Sure thing

**Comment by hugo19941994** [comment]
Added in version 1.0.1 (3997bc2ee87e720651544d1f43863c3874826fcc)

**Comment by pburgmer** [comment]
Thanks a lot
